dist: trusty
language: node_js
node_js:
- 14
cache:
  directories:
  - node_modules
before_install:
install: npm install
before_script:
script: 
  - npm run test
  - echo 'hellooo'
env:
  global:
  - NODE_ENV: test
